name: likray
description: Анонимное голосование учеников о школьном расписании (прототип).
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Управление состоянием
  flutter_riverpod: ^2.5.1

  # HTTP-клиент
  dio: ^5.4.3

  # Навигация
  go_router: ^14.0.2

  # Безопасное хранилище JWT
  flutter_secure_storage: ^9.2.2

  # Графики (для дашборда администратора)
  fl_chart: ^0.68.0

  # Работа с файлами и путями (экспорт CSV/PDF)
  path_provider: ^2.1.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
